name: Scrape and Commit

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Sarjataulukko.py
        run: python Sarjataulukko.py

      - name: Run Ottelu.py
        run: python Ottelu.py

      - name: Run PelatutOttelut.py
        run: python PelatutOttelut.py

      - name: Commit and push updates
        run: |
          git config --global user.name 'actions-user'
          git config --global user.email 'actions@github.com'
          git add Sarjataulukko.csv Sarjataulukko.md Ottelut.csv PelatutOttelut.csv PelatutOttelut.md TulevatOttelut.csv || true
          git commit -m "Automatic data update [skip ci]" || echo "No changes to commit"
          git push
