name: Scrape and Commit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'  # Runs at 7:00 UTC every day

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensure we have all history for proper updates
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run scraper
      run: |
        python scraper.py
        echo "Scraper completed"
        
    - name: Process data
      run: |
        python PelatutOttelut.py
        python Sarjataulukko.py
        echo "Data processing completed"
        
    - name: Debug file status
      run: |
        echo "Files status:"
        ls -la *.csv *.md
        
    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
    - name: Update timestamp
      run: |
        echo "$(date -u)" > timestamp.txt
        
    - name: Commit and push changes
      run: |
        git add -A
        git status
        
        # Force commit even if Git thinks there are no changes
        git commit -m "Automatic data update [skip ci]" || echo "No changes to commit"
        git push
