name: Scrape and Commit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'  # Runs at 7:00 UTC every day

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas playwright asyncio
        python -m playwright install chromium --with-deps
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Check internet connectivity
      run: |
        echo "Testing internet connectivity..."
        curl -I https://palloliitto.fi
        curl -I https://tulospalvelu.palloliitto.fi/
        
    - name: Run diagnostic script
      run: |
        echo "Running diagnostics..."
        python debug_script.py
        
    - name: Run scraper
      run: |
        echo "Running scraper with Playwright..."
        python scraper.py || echo "Scraper failed, will use fallback data"
      continue-on-error: true
        
    - name: Use fallback data
      run: |
        echo "Creating fallback data..."
        python fallback_data.py
        
    - name: Debug file outputs
      run: |
        echo "Listing screenshot and HTML files:"
        ls -la *.png || echo "No PNG files"
        ls -la *.html || echo "No HTML files"
        echo "Listing CSV files:"
        ls -la *.csv
        echo "Listing Markdown files:"
        ls -la *.md
        
    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
    - name: Commit and push if changed
      run: |
        echo "Checking for changes to commit..."
        git add -A
        git status
        
        # Always attempt to commit changes
        git commit -m "Automatic data update [skip ci]" || echo "No changes to commit"
        git push
