name: Run Football Stats Scraper

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * *"  # Run daily at 12:00 UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install chromium
          pip install requests bs4

      - name: Run Python scraper
        run: |
          python scraper.py
        
      - name: Upload artifacts for debugging
        if: always()  # Always run this step, even if scraper fails
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: debug-artifacts
          path: debug/
      
      - name: Commit and push if there are changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add tulokset.csv timestamp.txt
          git diff --staged --quiet || git commit -m "Update football stats [skip ci]"
          git push
