name: Scrape and Commit Data

on:
  schedule:
    - cron: "0 12 * * *"  # Ajaa joka p채iv채 klo 12 UTC
  workflow_dispatch:  # Mahdollistaa manuaalisen ajon GitHubista

jobs:
  scrape_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install playwright && playwright install

      - name: Run scraper
        run: python scraper.py

      - name: Force commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          timestamp=$(date -u)
          echo "Viimeisin p채ivitys: $timestamp" > timestamp.txt  # Pakottaa muutoksen
          git add tulokset.csv timestamp.txt
          git commit -m "P채ivitetty tulokset: $timestamp" || echo "Ei muutoksia commitattavaksi"
          git push
